name: PlatformIO CI

on:
  push:
    branches: [main, develop, feature/**]
  pull_request:
    branches: [main, develop]     
jobs:
  build-and-test:
    name: PlatformIO Test (native)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache PlatformIO packages
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-platformio-

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Run PlatformIO tests
        working-directory: ./Simple_Unit_Test
        run: |
          pio test -e native -v
